import type { AchievementDefinition } from '@/types/achievement';

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  {
    id: 'first_session',
    category: 'play',
    titleKey: 'achievementFirstSessionTitle',
    descriptionKey: 'achievementFirstSessionDescription',
    statKey: 'sessionsCreated',
    target: 1,
  },
  {
    id: 'first_finish',
    category: 'play',
    titleKey: 'achievementFirstFinishTitle',
    descriptionKey: 'achievementFirstFinishDescription',
    statKey: 'gamesCompleted',
    target: 1,
  },
  {
    id: 'size_4_clear',
    category: 'play',
    titleKey: 'achievementSize4Title',
    descriptionKey: 'achievementSize4Description',
    statKey: 'size4Wins',
    target: 1,
  },
  {
    id: 'size_6_clear',
    category: 'play',
    titleKey: 'achievementSize6Title',
    descriptionKey: 'achievementSize6Description',
    statKey: 'size6Wins',
    target: 1,
  },
  {
    id: 'expanded_clear',
    category: 'play',
    titleKey: 'achievementExpandedTitle',
    descriptionKey: 'achievementExpandedDescription',
    statKey: 'expandedWins',
    target: 1,
  },
  {
    id: 'combo_10',
    category: 'performance',
    titleKey: 'achievementCombo10Title',
    descriptionKey: 'achievementCombo10Description',
    statKey: 'bestCombo',
    target: 10,
  },
  {
    id: 'combo_25',
    category: 'performance',
    titleKey: 'achievementCombo25Title',
    descriptionKey: 'achievementCombo25Description',
    statKey: 'bestCombo',
    target: 25,
  },
  {
    id: 'combo_50',
    category: 'performance',
    titleKey: 'achievementCombo50Title',
    descriptionKey: 'achievementCombo50Description',
    statKey: 'bestCombo',
    target: 50,
  },
  {
    id: 'perfect_clear',
    category: 'performance',
    titleKey: 'achievementPerfectTitle',
    descriptionKey: 'achievementPerfectDescription',
    statKey: 'perfectGames',
    target: 1,
  },
  {
    id: 'lazy_clear',
    category: 'performance',
    titleKey: 'achievementLazyTitle',
    descriptionKey: 'achievementLazyDescription',
    statKey: 'lazyWins',
    target: 1,
  },
  {
    id: 'standard_clear',
    category: 'performance',
    titleKey: 'achievementStandardTitle',
    descriptionKey: 'achievementStandardDescription',
    statKey: 'standardWins',
    target: 1,
  },
  {
    id: 'manual_finisher',
    category: 'mastery',
    titleKey: 'achievementManualFinalTitle',
    descriptionKey: 'achievementManualFinalDescription',
    statKey: 'manualFinalClicks',
    target: 1,
  },
  {
    id: 'keyboard_only_clear',
    category: 'mastery',
    titleKey: 'achievementKeyboardOnlyTitle',
    descriptionKey: 'achievementKeyboardOnlyDescription',
    statKey: 'keyboardOnlyWins',
    target: 1,
  },
  {
    id: 'hidden_axis_clear',
    category: 'mastery',
    titleKey: 'achievementHiddenAxisTitle',
    descriptionKey: 'achievementHiddenAxisDescription',
    statKey: 'winsWithHiddenAxis',
    target: 1,
  },
  {
    id: 'hidden_final_layer_clear',
    category: 'mastery',
    titleKey: 'achievementHiddenFinalLayerTitle',
    descriptionKey: 'achievementHiddenFinalLayerDescription',
    statKey: 'winsWithHiddenFinalLayer',
    target: 1,
  },
  {
    id: 'story_apply',
    category: 'story',
    titleKey: 'achievementStoryApplyTitle',
    descriptionKey: 'achievementStoryApplyDescription',
    statKey: 'storyLevelsApplied',
    target: 1,
  },
  {
    id: 'story_training_clear',
    category: 'story',
    titleKey: 'achievementStoryTrainingTitle',
    descriptionKey: 'achievementStoryTrainingDescription',
    statKey: 'trainingStoryWins',
    target: 1,
  },
  {
    id: 'story_duel_clear',
    category: 'story',
    titleKey: 'achievementStoryDuelTitle',
    descriptionKey: 'achievementStoryDuelDescription',
    statKey: 'duelStoryWins',
    target: 1,
  },
  {
    id: 'replay_opened',
    category: 'social_future',
    titleKey: 'achievementReplayOpenTitle',
    descriptionKey: 'achievementReplayOpenDescription',
    statKey: 'replayOpenedCount',
    target: 1,
  },
  {
    id: 'replay_played',
    category: 'social_future',
    titleKey: 'achievementReplayPlayTitle',
    descriptionKey: 'achievementReplayPlayDescription',
    statKey: 'replayPlayedCount',
    target: 1,
  },
  {
    id: 'room_creator',
    category: 'social_future',
    titleKey: 'achievementRoomCreatorTitle',
    descriptionKey: 'achievementRoomCreatorDescription',
    statKey: 'roomsCreated',
    target: 1,
    futureOnly: true,
  },
  {
    id: 'room_joiner',
    category: 'social_future',
    titleKey: 'achievementRoomJoinerTitle',
    descriptionKey: 'achievementRoomJoinerDescription',
    statKey: 'roomsJoined',
    target: 1,
    futureOnly: true,
  },
  {
    id: 'chat_starter',
    category: 'social_future',
    titleKey: 'achievementChatStarterTitle',
    descriptionKey: 'achievementChatStarterDescription',
    statKey: 'messagesSent',
    target: 1,
    futureOnly: true,
  },
  {
    id: 'multiplayer_winner',
    category: 'social_future',
    titleKey: 'achievementMultiplayerWinnerTitle',
    descriptionKey: 'achievementMultiplayerWinnerDescription',
    statKey: 'multiplayerWins',
    target: 1,
    futureOnly: true,
  },
];
